package cajero_automatico;
import java.io.*;
import java.net.*;
import java.awt.Color;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;


public class Inicio_Cajero extends javax.swing.JPanel implements java.beans.Customizer {
    private Socket socket;
    private ObjectOutputStream outputStream;
    private ObjectInputStream inputStream;
    String host = "localhost"; // Dirección del servidor
    int puerto = 5000; // Puerto en el que el servidor escucha por conexiones
    private void conectar() {
    try {
        socket = new Socket(host, puerto);
        outputStream = new ObjectOutputStream(socket.getOutputStream());
        inputStream = new ObjectInputStream(socket.getInputStream());
    } catch (UnknownHostException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
}
    private Object bean;
    public Inicio_Cajero() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Panel_Movimientos = new java.awt.TextArea();
        Comenzar = new javax.swing.JButton();
        Ingresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Entrada_NCuenta = new javax.swing.JTextField();
        Retiro = new javax.swing.JButton();
        Deposito = new javax.swing.JButton();
        ConsultaSaldo = new javax.swing.JButton();
        Movimientos = new javax.swing.JButton();
        TextoActualizable = new javax.swing.JLabel();
        Retirar_Mensaje = new javax.swing.JButton();
        Depositar_Mensaje = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Entrada_PIN = new javax.swing.JTextField();
        Entrada_RD = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero_automatico/Imagenes/banco-de-venezuela-logo.png"))); // NOI18N
        Logo.setText("jLabel1");
        Logo.setMinimumSize(new java.awt.Dimension(500, 100));
        Logo.setPreferredSize(new java.awt.Dimension(1000, 300));
        jPanel1.add(Logo);
        jPanel1.add(Panel_Movimientos);

        Comenzar.setBackground(new java.awt.Color(0, 102, 153));
        Comenzar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Comenzar.setForeground(new java.awt.Color(255, 255, 255));
        Comenzar.setText("Comenzar");
        Comenzar.setAlignmentY(0.75F);
        Comenzar.setAutoscrolls(true);
        Comenzar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Comenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Comenzar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Comenzar.setPreferredSize(new java.awt.Dimension(200, 50));
        Comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(Comenzar);

        Ingresar.setBackground(new java.awt.Color(255, 51, 51));
        Ingresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("Ingresar");
        Ingresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ingresar.setPreferredSize(new java.awt.Dimension(200, 50));
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar);
        jPanel1.add(jSeparator1);

        Entrada_NCuenta.setBackground(new java.awt.Color(204, 204, 204));
        Entrada_NCuenta.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
        Entrada_NCuenta.setForeground(new java.awt.Color(0, 0, 0));
        Entrada_NCuenta.setText("Numero de cuenta");
        Entrada_NCuenta.setToolTipText("");
        Entrada_NCuenta.setPreferredSize(new java.awt.Dimension(400, 50));
        Entrada_NCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_NCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(Entrada_NCuenta);

        Retiro.setBackground(new java.awt.Color(255, 204, 51));
        Retiro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Retiro.setForeground(new java.awt.Color(255, 255, 255));
        Retiro.setText("Retiro");
        Retiro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Retiro.setPreferredSize(new java.awt.Dimension(200, 50));
        Retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetiroActionPerformed(evt);
            }
        });
        jPanel1.add(Retiro);

        Deposito.setBackground(new java.awt.Color(255, 204, 51));
        Deposito.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Deposito.setForeground(new java.awt.Color(255, 255, 255));
        Deposito.setText("Deposito");
        Deposito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Deposito.setPreferredSize(new java.awt.Dimension(200, 50));
        Deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositoActionPerformed(evt);
            }
        });
        jPanel1.add(Deposito);

        ConsultaSaldo.setBackground(new java.awt.Color(0, 102, 255));
        ConsultaSaldo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ConsultaSaldo.setForeground(new java.awt.Color(255, 255, 255));
        ConsultaSaldo.setText("Consultar Saldo");
        ConsultaSaldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConsultaSaldo.setPreferredSize(new java.awt.Dimension(200, 50));
        ConsultaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(ConsultaSaldo);

        Movimientos.setBackground(new java.awt.Color(0, 102, 255));
        Movimientos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Movimientos.setForeground(new java.awt.Color(255, 255, 255));
        Movimientos.setText("Movimientos");
        Movimientos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Movimientos.setPreferredSize(new java.awt.Dimension(200, 50));
        Movimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosActionPerformed(evt);
            }
        });
        jPanel1.add(Movimientos);

        TextoActualizable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoActualizable.setForeground(new java.awt.Color(0, 51, 51));
        TextoActualizable.setText("Espacio Para textos");
        jPanel1.add(TextoActualizable);

        Retirar_Mensaje.setBackground(new java.awt.Color(0, 102, 255));
        Retirar_Mensaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Retirar_Mensaje.setForeground(new java.awt.Color(255, 255, 255));
        Retirar_Mensaje.setText("Retirar");
        Retirar_Mensaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Retirar_Mensaje.setPreferredSize(new java.awt.Dimension(200, 50));
        Retirar_Mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retirar_MensajeActionPerformed(evt);
            }
        });
        jPanel1.add(Retirar_Mensaje);

        Depositar_Mensaje.setBackground(new java.awt.Color(0, 102, 255));
        Depositar_Mensaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Depositar_Mensaje.setForeground(new java.awt.Color(255, 255, 255));
        Depositar_Mensaje.setText("Depositar");
        Depositar_Mensaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Depositar_Mensaje.setPreferredSize(new java.awt.Dimension(200, 50));
        Depositar_Mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Depositar_MensajeActionPerformed(evt);
            }
        });
        jPanel1.add(Depositar_Mensaje);

        Regresar.setBackground(new java.awt.Color(0, 102, 255));
        Regresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Regresar");
        Regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Regresar.setPreferredSize(new java.awt.Dimension(200, 50));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar);

        Salir.setBackground(new java.awt.Color(0, 102, 255));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salir.setPreferredSize(new java.awt.Dimension(200, 50));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir);

        Entrada_PIN.setBackground(new java.awt.Color(204, 204, 204));
        Entrada_PIN.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
        Entrada_PIN.setForeground(new java.awt.Color(0, 0, 0));
        Entrada_PIN.setText("PIN");
        Entrada_PIN.setToolTipText("");
        Entrada_PIN.setPreferredSize(new java.awt.Dimension(400, 50));
        Entrada_PIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_PINActionPerformed(evt);
            }
        });
        jPanel1.add(Entrada_PIN);

        Entrada_RD.setBackground(new java.awt.Color(204, 204, 204));
        Entrada_RD.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
        Entrada_RD.setForeground(new java.awt.Color(0, 0, 0));
        Entrada_RD.setToolTipText("");
        Entrada_RD.setPreferredSize(new java.awt.Dimension(400, 50));
        Entrada_RD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_RDActionPerformed(evt);
            }
        });
        jPanel1.add(Entrada_RD);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    //Voids para invisibilizar o visibilizar elementos
    public void IC(){
        Retiro.setVisible(false);
        Deposito.setVisible(false);
        ConsultaSaldo.setVisible(false);
        Movimientos.setVisible(false);
        TextoActualizable.setVisible(false);
        Entrada_NCuenta.setVisible(false);
        Entrada_PIN.setVisible(false);
        Ingresar.setVisible(false);
        Retirar_Mensaje.setVisible(false);
        Depositar_Mensaje.setVisible(false);
        Logo.setVisible(true);
        Comenzar.setVisible(true);
        Regresar.setVisible(false);
        Salir.setVisible(false);
        Entrada_RD.setVisible(false);
        Panel_Movimientos.setVisible(false);
        //Posicionado
        
        //Conectar
        conectar();
    }
    private void invisibilizarMenu(){
        //Haciendo invisibles los elementos del menu para las operaciones 
        //Necesarias, en este caso botones
        Retiro.setVisible(false);
        Deposito.setVisible(false);
        ConsultaSaldo.setVisible(false);
        Movimientos.setVisible(false);
        Salir.setVisible(false);
    }
    private void iniciarMenu(){ 
        Retiro.setVisible(true);
        Deposito.setVisible(true);
        ConsultaSaldo.setVisible(true);
        Movimientos.setVisible(true);
        Salir.setVisible(true);
        TextoActualizable.setVisible(true);
        TextoActualizable.setForeground(Color.BLACK);
        TextoActualizable.setText("Bienvenido\nBanco de Venezuela");
    }
    private void salida(){
        CerrarSesion();
        Retiro.setVisible(false);
        Deposito.setVisible(false);
        ConsultaSaldo.setVisible(false);
        Movimientos.setVisible(false);
        TextoActualizable.setVisible(false);
        Entrada_NCuenta.setVisible(false);
        Entrada_PIN.setVisible(false);
        Ingresar.setVisible(false);
        Retirar_Mensaje.setVisible(false);
        Depositar_Mensaje.setVisible(false);
        Logo.setVisible(true);
        Comenzar.setVisible(true);
        Panel_Movimientos.setVisible(false);
        
    }
    private void regreso(){
        Retiro.setVisible(false);
        Deposito.setVisible(false);
        ConsultaSaldo.setVisible(false);
        Movimientos.setVisible(false);
        TextoActualizable.setVisible(false);
        Entrada_NCuenta.setVisible(false);
        Entrada_PIN.setVisible(false);
        Ingresar.setVisible(false);
        Retirar_Mensaje.setVisible(false);
        Depositar_Mensaje.setVisible(false);
        Logo.setVisible(true);
        Comenzar.setVisible(false);
        Entrada_RD.setVisible(false);
        //Iniciar menu
        Retiro.setVisible(true);
        Deposito.setVisible(true);
        ConsultaSaldo.setVisible(true);
        Movimientos.setVisible(true);
        TextoActualizable.setVisible(true);
        Salir.setVisible(true);
        TextoActualizable.setForeground(Color.BLACK);
        TextoActualizable.setText("Bienvenido\nBanco de Venezuela");
        Panel_Movimientos.setVisible(false);
    }
    //Voids de acciones del cajero
    private void CerrarSesion(){
    
    }
    private boolean ValidarDatos(String NCuenta, String PIN){
    
        return true;
    }
    private boolean Retirar(){
    
        return true;
    }
    private boolean Depositar (){
        
        return true;
    }
    // Terminan Voids del cajero
    private void ComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarActionPerformed
        //Haciendo invisible el boton de comenzar y haciendo visibles las cajas de texto para Numero de cuenta y PIN ademas del doton de ingreso
        Comenzar.setVisible(false);
        Entrada_NCuenta.setVisible(true);
        Entrada_PIN.setVisible(true);
        Ingresar.setVisible(true);
         try (Socket cliente = new Socket(host, puerto)) {
             //Conectar con el servidor
            } catch (IOException e) {
                e.printStackTrace();
            }
    }//GEN-LAST:event_ComenzarActionPerformed

    private void Entrada_NCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_NCuentaActionPerformed
        Entrada_NCuenta.setText("");
    }//GEN-LAST:event_Entrada_NCuentaActionPerformed

    private void RetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetiroActionPerformed
        invisibilizarMenu();
        Entrada_RD.setVisible(true);
        Retirar_Mensaje.setVisible(true);
        Regresar.setVisible(true);
        TextoActualizable.setText("Ingrese la cantidad a retirar");
        TextoActualizable.setForeground(Color.BLUE);
    }//GEN-LAST:event_RetiroActionPerformed

    private void Retirar_MensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retirar_MensajeActionPerformed
        
        
        // Enviando la accion y cantidad al servidor
        
        //Esperando Respuesta del servidor
        //Ya sea true para regresar el balance actualizado
        //o False por no contar con fondos insuficientes
    }//GEN-LAST:event_Retirar_MensajeActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // Salir del sistema
        salida();
        Salir.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void Entrada_PINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_PINActionPerformed
        Entrada_PIN.setText("");
    }//GEN-LAST:event_Entrada_PINActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        /* Envia los datos ingresados al servidor para confirmar que existe el
        cliente y si devuelve true ingresa a las demas funciones del cajero
        en caso contrario manda mensaje de error*/
        
        if(ValidarDatos(Entrada_NCuenta.getText(),Entrada_PIN.getText())== true){
            //El ingreso a la cuenta ha sido establecido con el servidor,
            //se permite realizar operaciones
            Logo.setVisible(false);
            Ingresar.setVisible(false);
            Entrada_NCuenta.setVisible(false);
            Entrada_PIN.setVisible(false);
            Entrada_NCuenta.setText("Numero de Cuenta");
            Entrada_PIN.setText("PIN");
            iniciarMenu();
        }
        else{
            Entrada_NCuenta.setText("Numero de Cuenta");
            Entrada_PIN.setText("PIN");
            TextoActualizable.setVisible(true);
            TextoActualizable.setForeground(Color.red);
            TextoActualizable.setText("Usuario o PIN incorrectos");
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private void DepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositoActionPerformed
        invisibilizarMenu();
        Entrada_RD.setVisible(true);
        Depositar_Mensaje.setVisible(true);
        Regresar.setVisible(true);
        TextoActualizable.setText("Ingrese la cantidad a depositar");
        TextoActualizable.setForeground(Color.BLUE);
    }//GEN-LAST:event_DepositoActionPerformed

    private void ConsultaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaSaldoActionPerformed
        invisibilizarMenu();
        Regresar.setVisible(true);
        TextoActualizable.setForeground(Color.BLUE);
        String Saldo = "";
        //Lectura de la base de datos
        // Actualizar el contenido del banner actualizable con la el
        //saldo de la base de datos
        TextoActualizable.setText(Saldo);
    }//GEN-LAST:event_ConsultaSaldoActionPerformed

    private void MovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosActionPerformed
        invisibilizarMenu();
        Regresar.setVisible(true);
        TextoActualizable.setVisible(false);
        Panel_Movimientos.setVisible(true);
        TextoActualizable.setForeground(Color.BLUE);
        String MovimientosC = "";
        //Lectura de la base de datos
        // Actualizar el contenido del scroll panel actualizable con la el
        //movimientos de la base de datos
        Panel_Movimientos.setText(MovimientosC);
    }//GEN-LAST:event_MovimientosActionPerformed

    private void Depositar_MensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Depositar_MensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Depositar_MensajeActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
       Regresar.setVisible(false);
       regreso(); 
    }//GEN-LAST:event_RegresarActionPerformed

    private void Entrada_RDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_RDActionPerformed
        Entrada_RD.setText("");
    }//GEN-LAST:event_Entrada_RDActionPerformed

    Thread thread =new Thread(() -> {
            try {
                ServerSocket servidor = new ServerSocket(puerto);
                while (true) {
                    Socket conexion = servidor.accept();
                }
            } catch (IOException e) {
            }
     });
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comenzar;
    private javax.swing.JButton ConsultaSaldo;
    private javax.swing.JButton Depositar_Mensaje;
    private javax.swing.JButton Deposito;
    private javax.swing.JTextField Entrada_NCuenta;
    private javax.swing.JTextField Entrada_PIN;
    private javax.swing.JTextField Entrada_RD;
    private javax.swing.JButton Ingresar;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Movimientos;
    private java.awt.TextArea Panel_Movimientos;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Retirar_Mensaje;
    private javax.swing.JButton Retiro;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel TextoActualizable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
